<?php 
	session_start();
	include('includes/global.php');
	$id="nothing";
	if($_SESSION['user']){	
		session_destroy();
		obtenerID('nothing');
		header("location:inicio.php");
	}
	else{
		header("location:inicio.php");
	}
?>